.TH "src/mpk1/blk978/mpk/412-06_fc.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mpk1/blk978/mpk/412-06_fc.h
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <libvork/412\-06_wire\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcell_412_06_target_strobe\fP"
.br
.RI "Данные ячейки 6МЯ-412-06 по целевому стробу "
.ti -1c
.RI "struct \fBcell_412_06_sim_object\fP"
.br
.RI "Данные ячейки 6МЯ-412-06 по имитируемом объекту "
.ti -1c
.RI "struct \fBcell_412_06_sim_strobe\fP"
.br
.RI "Данные ячейки 6МЯ-412-06 по имитационному стробу "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
