.TH "src/mpk1/blk223/mpk Directory Reference" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mpk1/blk223/mpk Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB412\-06_fc\&.h\fP"
.br
.ti -1c
.RI "file \fBc223\&.h\fP"
.br
.RI "Параметры драйвера (прошивки) для ячейки 9ДЯ-223\&. "
.in -1c
