.TH "src/mpk1/blk223/mpk/c223.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mpk1/blk223/mpk/c223.h \- Параметры драйвера (прошивки) для ячейки 9ДЯ-223\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEV_FC_T_OFFS\fP   0x10000"
.br
.RI "Смещение региона памяти для файла целевого ФУ\&. "
.ti -1c
.RI "#define \fBDEV_FC_I_OFFS\fP   0x20000"
.br
.RI "Смещение региона памяти для файла имитационного ФУ\&. "
.in -1c
.SH "Detailed Description"
.PP 
Параметры драйвера (прошивки) для ячейки 9ДЯ-223\&. 

Описания регистров управления прошивки, регионов памяти, констант и определений\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEV_FC_I_OFFS   0x20000"

.PP
Смещение региона памяти для файла имитационного ФУ\&. 
.SS "#define DEV_FC_T_OFFS   0x10000"

.PP
Смещение региона памяти для файла целевого ФУ\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
