.TH "CalibStrobeOutput" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CalibStrobeOutput
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <minDefs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBnstr\fP"
.br
.ti -1c
.RI "\fBPolarized\fP< std::vector< std::complex< double > > > \fBcalib_nonvirt\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBPolarized\fP<std::vector<std::complex<double> > > CalibStrobeOutput::calib_nonvirt"

.SS "uint32_t CalibStrobeOutput::nstr"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
