.TH "src/gui/callbacks.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui/callbacks.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBModelNS23817A620S1823::Complex32x32i\fP"
.br
.ti -1c
.RI "struct \fBModelNS23817A620S1823::Complex32x32df\fP"
.br
.ti -1c
.RI "struct \fBModelNS23817A620S1823::Value\fP"
.br
.ti -1c
.RI "struct \fBModelNS23817A620S1823::Callback\fP"
.br
.ti -1c
.RI "struct \fBModelNS23817A620S1823::Callbacks\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBModelNS23817A620S1823\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBModelNS23817A620S1823::Cut\fP { \fBModelNS23817A620S1823::CUT_ADC\fP = 1, \fBModelNS23817A620S1823::CUT_QUADR\fP = 2, \fBModelNS23817A620S1823::CUT_PFTP\fP = 3, \fBModelNS23817A620S1823::CUT_PSP\fP = 4, \fBModelNS23817A620S1823::CUT_418_01_OUTPUT\fP = 6, \fBModelNS23817A620S1823::CUT_418_02_OUTPUT\fP = 8, \fBModelNS23817A620S1823::CUT_232_OUTPUT\fP = 10, \fBModelNS23817A620S1823::CUT_ADC\fP = 1, \fBModelNS23817A620S1823::CUT_QUADR\fP = 2, \fBModelNS23817A620S1823::CUT_PFTP\fP = 3, \fBModelNS23817A620S1823::CUT_PSP\fP = 4, \fBModelNS23817A620S1823::CUT_418_01_OUTPUT\fP = 6, \fBModelNS23817A620S1823::CUT_418_02_OUTPUT\fP = 8, \fBModelNS23817A620S1823::CUT_232_OUTPUT\fP = 10 }"
.br
.ti -1c
.RI "enum \fBModelNS23817A620S1823::CutMode\fP { \fBModelNS23817A620S1823::tfpComplexOutBoth\fP = 2, \fBModelNS23817A620S1823::cutModeNone\fP = 10000, \fBModelNS23817A620S1823::tfpComplexOutBoth\fP = 2, \fBModelNS23817A620S1823::cutModeNone\fP = 10000 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
