.TH "complex32" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex32 \- Структура 32-разрядного комплексного числа\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <223fc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBre\fP"
.br
.RI "Действительная часть числа\&. "
.ti -1c
.RI "int32_t \fBim\fP"
.br
.RI "Мнимая часть числа\&. "
.in -1c
.SH "Detailed Description"
.PP 
Структура 32-разрядного комплексного числа\&. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t complex32::im"

.PP
Мнимая часть числа\&. 
.SS "int32_t complex32::re"

.PP
Действительная часть числа\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
