.TH "src/gui/config.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui/config.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/property_tree/ptree\&.hpp>\fP
.br
\fC#include <boost/property_tree/json_parser\&.hpp>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <libvork/parsig\&.h>\fP
.br
\fC#include <libvork/e2trpr\&.h>\fP
.br
\fC#include <libvork/e2trims\&.h>\fP
.br
\fC#include <model/modelInterface\&.h>\fP
.br
\fC#include 'messages\&.h'\fP
.br
\fC#include 'dpParams\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
