.TH "src/dfGroups.cpp" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dfGroups.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br
\fC#include 'dfGroups\&.h'\fP
.br
\fC#include 'sharedConst\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBModelNS23817A620S1823\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const double \fBModelNS23817A620S1823::rayWidthByUForM\fP = 0\&.0205"
.br
.ti -1c
.RI "static const double \fBModelNS23817A620S1823::rayWidthByUForSM\fP = 0\&.011"
.br
.ti -1c
.RI "static const double \fBModelNS23817A620S1823::rayWidthByUForMrik\fP = 0\&.008"
.br
.ti -1c
.RI "static const double \fBModelNS23817A620S1823::rayWidthByVForM\fP = 0\&.0426"
.br
.ti -1c
.RI "static const double \fBModelNS23817A620S1823::rayWidthByVForSM\fP = 0\&.0141"
.br
.ti -1c
.RI "static const double \fBModelNS23817A620S1823::rayWidthByVForMrik\fP = 0\&.0118"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
