.TH "include/model/e2trkp.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/model/e2trkp.h
.SH SYNOPSIS
.br
.PP
\fC#include <libvork/rtnetxx\&.h>\fP
.br
\fC#include <libvork/e2trkp\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTrkpHeader\fP"
.br
.ti -1c
.RI "struct \fBE2Trkp\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef FloatComplex \fBComplexFloat\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint32_t \fBtrkpCoefsNum\fP = 1560"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef FloatComplex \fBComplexFloat\fP"

.SH "Variable Documentation"
.PP 
.SS "const uint32_t trkpCoefsNum = 1560"

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
