.TH "include/model/e2trimts.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/model/e2trimts.h
.SH SYNOPSIS
.br
.PP
\fC#include <libvork/e2trims\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBmaxImitObjects\fP   MAX_IMIT_OBJECTS"
.br
.ti -1c
.RI "#define \fBmaxImitStrobes\fP   MAX_IMIT_STROBES"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define maxImitObjects   MAX_IMIT_OBJECTS"

.SS "#define maxImitStrobes   MAX_IMIT_STROBES"

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
