.TH "src/mpk1/blk223/fcmgmt.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mpk1/blk223/fcmgmt.h \- Планировщик фукнционального управления (ФУ)\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <libvork/e2trpr\&.h>\fP
.br
\fC#include <libvork/e2trims\&.h>\fP
.br
\fC#include <libvork/e2mask\&.h>\fP
.br
\fC#include <libvork/e2trkp\&.h>\fP
.br
\fC#include <libvork/e2ippa\&.h>\fP
.br
\fC#include 'fcquantum\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdirect_trpr_to_fc\fP (const E2TRPR &msg_trpr, \fBfc_map\fP &fcmap)"
.br
.RI "Функция перенаправляет сообщение ТРПР в контейнер ФУ\&. "
.ti -1c
.RI "int \fBdirect_trims_to_fc\fP (const TrimtsMsg &msg_trims, \fBfc_map\fP &fcmap)"
.br
.RI "Функция перенаправляет сообщение ТРИМС в контейнер ФУ\&. "
.ti -1c
.RI "void \fBinit_fc_defaults\fP ()"
.br
.RI "Инициализация данных ФУ по умолчанию при старте ФПО\&. "
.ti -1c
.RI "void \fBupdate_afr\fP (const \fBTRKP\fP &msg_afr)"
.br
.RI "Функция обновляет хранимую структуру АФР новыми данными\&. "
.ti -1c
.RI "void \fBupdate_clb\fP (const \fBTRKP\fP &msg_clb)"
.br
.RI "Функция обновляет хранимую структуру КЛБ новыми данными\&. "
.ti -1c
.RI "void \fBupdate_mask\fP (const \fBMASK\fP &msg_mask)"
.br
.RI "Функция обновляет хранимую маску каналов новыми данными\&. "
.ti -1c
.RI "void \fBupdate_ippa\fP (const E2IPPA *msg_ippa)"
.br
.RI "Функция обновляет хранимое сообщение Е2ИППА новыми данными\&. "
.ti -1c
.RI "int \fBdrop_old_fc\fP (\fBfc_map\fP &fcmap, int64_t stroke)"
.br
.RI "Функция удаляет просроченное ФУ из контейнера ФУ\&. "
.ti -1c
.RI "int \fBdrop_fc_exceeded_queue_limit\fP (\fBfc_map\fP &fcmap)"
.br
.RI "Функция удаляет ФУ, превышающее допустимый размер очереди ФУ\&. "
.ti -1c
.RI "void \fBdelete_fcq\fP (const \fBfcq\fP *fcqp)"
.br
.RI "Функция удаляет заданный квант ФУ из контейнера ФУ\&. "
.ti -1c
.RI "\fBfcq\fP * \fBextract_fc\fP (\fBfc_map\fP &fcmap, int64_t stroke)"
.br
.RI "Функция извлекает заданный квант ФУ из контейнера ФУ\&. "
.ti -1c
.RI "\fBfcq\fP * \fBget_fc_quant\fP (\fBfc_map\fP &fcmap, int64_t stroke)"
.br
.RI "Функция возвращает указатель на структуру ФУ для заданного номера такта\&. "
.in -1c
.SH "Detailed Description"
.PP 
Планировщик фукнционального управления (ФУ)\&. 

Функции для формирования квантов ФУ, их поиска и удаления\&. 
.SH "Function Documentation"
.PP 
.SS "void delete_fcq (const \fBfcq\fP * fcqp)"

.PP
Функция удаляет заданный квант ФУ из контейнера ФУ\&. Функция производит высвобождение блока памяти, которое занимает указанный квант ФУ\&. 
.PP
\fBParameters\fP
.RS 4
\fIfcqp\fP Указатель на квант ФУ, подлежащий удалению\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Ничего не возвращает\&. 
.RE
.PP

.SS "int direct_trims_to_fc (const TrimtsMsg & msg_trims, \fBfc_map\fP & fcmap)"

.PP
Функция перенаправляет сообщение ТРИМС в контейнер ФУ\&. Функция получает указатель на квант ФУ в контейнере ФУ для нужного такта (при необходимости он создается) и копирует входящее сообщение ТРИМС в данный квант на нужный такт\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg_trims\fP Данные сообщения ТРИМС\&. 
.br
\fIfcmap\fP Ссылка на контейнер ФУ\&. 
.RE
.PP
\fBReturns\fP
.RS 4
В случае успешной обработки ТРИМС вернет EXIT_SUCCESS\&. 
.PP
В случае ошибки вернет EXIT_FAILURE\&. 
.RE
.PP

.SS "int direct_trpr_to_fc (const E2TRPR & msg_trpr, \fBfc_map\fP & fcmap)"

.PP
Функция перенаправляет сообщение ТРПР в контейнер ФУ\&. Функция получает указатель на квант ФУ в контейнере ФУ для нужного такта (при необходимости он создается) и копирует входящее сообщение ТРПР в данный квант на нужный такт\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg_trpr\fP Данные сообщения ТРПР\&. 
.br
\fIfcmap\fP Ссылка на контейнер ФУ\&. 
.RE
.PP
\fBReturns\fP
.RS 4
В случае успешной обработки ТРПР вернет EXIT_SUCCESS\&. 
.PP
В случае ошибки вернет EXIT_FAILURE\&. 
.RE
.PP

.SS "int drop_fc_exceeded_queue_limit (\fBfc_map\fP & fcmap)"

.PP
Функция удаляет ФУ, превышающее допустимый размер очереди ФУ\&. Функция удаляет кванты ФУ, превышающие допустимый размер очереди ФУ\&. В первую очередь удаляются самые старые кванты ФУ (по номеру такта исполнения)\&. 
.PP
\fBParameters\fP
.RS 4
\fIfcmap\fP Ссылка на контейнер ФУ\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Возвращает количество удаленных квантов ФУ\&. 
.RE
.PP

.SS "int drop_old_fc (\fBfc_map\fP & fcmap, int64_t stroke)"

.PP
Функция удаляет просроченное ФУ из контейнера ФУ\&. Функция производит последовательный перебор всех квантов ФУ, хранящихся в контенейре ФУ\&. Для каждого найденного кванта производится сравнение текущего номера такта и номера такта сообщения\&. Если номер такта сообщения меньше текущего номера такта (ФУ просрочено), то данный квант удаляется, в журнал добавляется соответствующая запись, а также увеличивается счетчик просроченных сообщений в блоке статистики\&. 
.PP
\fBParameters\fP
.RS 4
\fIfcmap\fP Ссылка на контейнер ФУ\&. 
.br
\fIstroke\fP Текущий номер такта\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Возвращает количество удаленных просроченных ФУ\&. 
.RE
.PP

.SS "\fBfcq\fP * extract_fc (\fBfc_map\fP & fcmap, int64_t stroke)"

.PP
Функция извлекает заданный квант ФУ из контейнера ФУ\&. Функция производит поиск в контейнере ФУ кванта на заданный такт\&. Если такой квант найден, он копируется в новый объект, который и будет возвращен функцией, а квант ФУ в контейнере ФУ уничтожается\&. Если же квант ФУ на заданный такт не найден, функция возвращает NULL\&. 
.PP
\fBParameters\fP
.RS 4
\fIfcmap\fP Ссылка на контейнер ФУ\&. 
.br
\fIstroke\fP Текущий номер такта\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Возвращает указатель на найденный квант ФУ\&. 
.PP
Возвращает NULL, если ФУ на заданный такт не найдено\&. 
.RE
.PP

.SS "\fBfcq\fP * get_fc_quant (\fBfc_map\fP & fcmap, int64_t stroke)"

.PP
Функция возвращает указатель на структуру ФУ для заданного номера такта\&. Функция производит поиск в контейнере ФУ кванта на заданный такт\&. Если такой квант найден, он копируется в новый объект, который и будет возвращен функцией\&. Если же квант ФУ на заданный такт не найден, распределяется память под новый объект кванта ФУ, в данном объекте инициализируются маски каналов актуальной маской, распределяется память под буферы сообщений Е2ТРПР и Е2ТРИМС и итоговый квант ФУ помещается в контейнер-очередь ФУ\&. Также увеличивается счетчик статистики созданных квантов ФУ\&. 
.PP
\fBParameters\fP
.RS 4
\fIfcmap\fP Ссылка на контейнер ФУ\&. 
.br
\fIstroke\fP Текущий номер такта\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Возвращает указатель на найденный квант ФУ\&. 
.RE
.PP

.SS "void init_fc_defaults ()"

.PP
Инициализация данных ФУ по умолчанию при старте ФПО\&. Функция производит сброс используемых масок каналов\&. 
.PP
\fBReturns\fP
.RS 4
Ничего не возвращает\&. 
.RE
.PP

.SS "void update_afr (const \fBTRKP\fP & msg_afr)"

.PP
Функция обновляет хранимую структуру АФР новыми данными\&. Функция копирует содержимое входящего сообщения АФР во внутреннюю структуру хранения\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg_afr\fP Данные сообщения АФР\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Ничего не возвращает\&. 
.RE
.PP

.SS "void update_clb (const \fBTRKP\fP & msg_clb)"

.PP
Функция обновляет хранимую структуру КЛБ новыми данными\&. Функция копирует содержимое входящего сообщения КЛБ во внутреннюю структуру хранения\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg_clb\fP Данные сообщения КЛБ\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Ничего не возвращает\&. 
.RE
.PP

.SS "void update_ippa (const E2IPPA * msg_ippa)"

.PP
Функция обновляет хранимое сообщение Е2ИППА новыми данными\&. Функция копирует содержимое входящего сообщения Е2ИППА во внутреннюю структуру хранения\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg_mask\fP Данные сообщения ИППА\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Ничего не возвращает\&. 
.RE
.PP

.SS "void update_mask (const \fBMASK\fP & msg_mask)"

.PP
Функция обновляет хранимую маску каналов новыми данными\&. Функция копирует содержимое входящего сообщения Е2МАСК во внутреннюю структуру хранения\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg_mask\fP Данные сообщения МАСК\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Ничего не возвращает\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
