.TH "src/mpk1/blk223/fcquantum.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mpk1/blk223/fcquantum.h \- Описание структуры кванта ФУ\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <libvork/e2mask\&.h>\fP
.br
\fC#include <libvork/e2trkp\&.h>\fP
.br
\fC#include <libvork/e2trpr\&.h>\fP
.br
\fC#include <libvork/e2trims\&.h>\fP
.br
\fC#include <libvork/e2ippa\&.h>\fP
.br
\fC#include '223fc\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfcq\fP"
.br
.RI "Квант ФУ для ячейки (тип)\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef EUMASK_CM \fBMASK\fP"
.br
.ti -1c
.RI "typedef EUTRKP_CM_Rx \fBTRKP\fP"
.br
.ti -1c
.RI "typedef std::map< int64_t, \fBfcq\fP * > \fBfc_map\fP"
.br
.RI "Контейнер для хранения массива ФУ для ячейки (тип)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Описание структуры кванта ФУ\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef std::map<int64_t, \fBfcq\fP*> \fBfc_map\fP"

.PP
Контейнер для хранения массива ФУ для ячейки (тип)\&. 
.SS "typedef EUMASK_CM \fBMASK\fP"

.SS "typedef EUTRKP_CM_Rx \fBTRKP\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
