.TH "fillAr" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fillAr
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgenerateString\fP (size)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBarCoefsByStationType\fP = [ 192, 1080, 96 ]"
.br
.ti -1c
.RI "list \fBstationType\fP = [ 'voronezhM', 'voronezhSM', 'Mrik' ]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "fillAr\&.generateString ( size)"

.SH "Variable Documentation"
.PP 
.SS "list fillAr\&.arCoefsByStationType = [ 192, 1080, 96 ]"

.SS "list fillAr\&.stationType = [ 'voronezhM', 'voronezhSM', 'Mrik' ]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
