.TH "gnuplotio::plotting_empty_container" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::plotting_empty_container
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.PP
Inherits std::length_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBplotting_empty_container\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gnuplotio::plotting_empty_container::plotting_empty_container ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
