.TH "gnuplotio::ModeAutoDecoder< T, typename boost::enable_if_c<(ArrayTraits< T >::depth==2) &&!ArrayTraits< T >::allow_auto_unwrap >::type >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::ModeAutoDecoder< T, typename boost::enable_if_c<(ArrayTraits< T >::depth==2) &&!ArrayTraits< T >::allow_auto_unwrap >::type >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBMode2D\fP \fBmode\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef \fBMode2D\fP \fBgnuplotio::ModeAutoDecoder\fP< T, typename boost::enable_if_c<(\fBArrayTraits\fP< T >::depth==2) &&!\fBArrayTraits\fP< T >::allow_auto_unwrap >::type >::mode"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
