.TH "gnuplotio::is_like_stl_container< T >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::is_like_stl_container< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef boost::mpl::and_< typename has_value_type< T >::type, typename has_const_iterator< T >::type, boost::mpl::not_< \fBdont_treat_as_stl_container\fP< T > > > \fBtype\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = type::value"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef boost::mpl::and_< typename has_value_type<T>::type, typename has_const_iterator<T>::type, boost::mpl::not_<\fBdont_treat_as_stl_container\fP<T> > > \fBgnuplotio::is_like_stl_container\fP< T >::type"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > const bool \fBgnuplotio::is_like_stl_container\fP< T >::value = type::value\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
