.TH "gnuplotio::BinarySender< boost::uint16_t >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::BinarySender< boost::uint16_t >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.PP
Inherits \fBgnuplotio::FlatBinarySender< boost::uint16_t >\fP\&.
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBgnuplotio::FlatBinarySender< boost::uint16_t >\fP
.in +1c
.ti -1c
.RI "static void \fBsend\fP (std::ostream &stream, const boost::uint16_t &v)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
