.TH "gnuplotio::Error_WasNotContainer" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::Error_WasNotContainer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBsubiter_type\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef void \fBgnuplotio::Error_WasNotContainer::subiter_type\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
