.TH "gnuplotio::GnuplotFeedback" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::GnuplotFeedback
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGnuplotFeedback\fP ()"
.br
.ti -1c
.RI "virtual \fB~GnuplotFeedback\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBfilename\fP () const =0"
.br
.ti -1c
.RI "virtual FILE * \fBhandle\fP () const =0"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBGnuplotFeedback\fP (const \fBGnuplotFeedback\fP &)"
.br
.ti -1c
.RI "const \fBGnuplotFeedback\fP & \fBoperator=\fP (const \fBGnuplotFeedback\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gnuplotio::GnuplotFeedback::GnuplotFeedback ()\fC [inline]\fP"

.SS "virtual gnuplotio::GnuplotFeedback::~GnuplotFeedback ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "gnuplotio::GnuplotFeedback::GnuplotFeedback (const \fBGnuplotFeedback\fP &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::string gnuplotio::GnuplotFeedback::filename () const\fC [pure virtual]\fP"

.SS "virtual FILE * gnuplotio::GnuplotFeedback::handle () const\fC [pure virtual]\fP"

.SS "const \fBGnuplotFeedback\fP & gnuplotio::GnuplotFeedback::operator= (const \fBGnuplotFeedback\fP &)\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
