.TH "gnuplotio::dont_treat_as_stl_container< T >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::dont_treat_as_stl_container< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef boost::mpl::bool_< false > \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef boost::mpl::bool_<false> \fBgnuplotio::dont_treat_as_stl_container\fP< T >::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
