.TH "gnuplotio::TextSender< char >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::TextSender< char >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.PP
Inherits \fBgnuplotio::CastIntTextSender< char >\fP\&.
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBgnuplotio::CastIntTextSender< char >\fP
.in +1c
.ti -1c
.RI "static void \fBsend\fP (std::ostream &stream, const char &v)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
