.TH "gnuplotio::ArrayTraitsDefaults< V >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::ArrayTraitsDefaults< V >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef V \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBis_container\fP = true"
.br
.ti -1c
.RI "static const bool \fBallow_auto_unwrap\fP = true"
.br
.ti -1c
.RI "static const size_t \fBdepth\fP = \fBArrayTraits\fP<V>::depth + 1"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename V > typedef V \fBgnuplotio::ArrayTraitsDefaults\fP< V >::value_type"

.SH "Member Data Documentation"
.PP 
.SS "template<typename V > const bool \fBgnuplotio::ArrayTraitsDefaults\fP< V >::allow_auto_unwrap = true\fC [static]\fP"

.SS "template<typename V > const size_t \fBgnuplotio::ArrayTraitsDefaults\fP< V >::depth = \fBArrayTraits\fP<V>::depth + 1\fC [static]\fP"

.SS "template<typename V > const bool \fBgnuplotio::ArrayTraitsDefaults\fP< V >::is_container = true\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
