.TH "gnuplotio::ModeText" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::ModeText
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBis_text\fP = 1"
.br
.ti -1c
.RI "static const bool \fBis_binfmt\fP = 0"
.br
.ti -1c
.RI "static const bool \fBis_size\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const bool gnuplotio::ModeText::is_binfmt = 0\fC [static]\fP"

.SS "const bool gnuplotio::ModeText::is_size = 0\fC [static]\fP"

.SS "const bool gnuplotio::ModeText::is_text = 1\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
