.TH "gnuplotio::ArrayTraits< T & >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::ArrayTraits< T & >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.PP
Inherits \fBgnuplotio::ArrayTraits< T, Enable >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBgnuplotio::ArrayTraits< T, Enable >\fP
.in +1c
.ti -1c
.RI "typedef \fBError_WasNotContainer\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBError_WasNotContainer\fP \fBrange_type\fP"
.br
.in -1c

Static Public Member Functions inherited from \fBgnuplotio::ArrayTraits< T, Enable >\fP
.in +1c
.ti -1c
.RI "static \fBrange_type\fP \fBget_range\fP (const T &)"
.br
.in -1c

Static Public Attributes inherited from \fBgnuplotio::ArrayTraits< T, Enable >\fP
.in +1c
.ti -1c
.RI "static const bool \fBis_container\fP = false"
.br
.ti -1c
.RI "static const bool \fBallow_auto_unwrap\fP = false"
.br
.ti -1c
.RI "static const size_t \fBdepth\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
