.TH "src/gui/guiapp.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui/guiapp.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QShortcut>\fP
.br
\fC#include <QTime>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include 'messages\&.h'\fP
.br
\fC#include 'sharedGuiTypes\&.h'\fP
.br
\fC#include 'dpParams\&.h'\fP
.br
\fC#include <model/modelInterface\&.h>\fP
.br
\fC#include '\&.\&./trpr\&.h'\fP
.br
\fC#include '\&.\&./ippa\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGuiApp\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
