.TH "src/inputBundle.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/inputBundle.h
.SH SYNOPSIS
.br
.PP
\fC#include <model/RPC\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "optional< Result< \fBModelInputBundle\fP > > \fBLoadBundle\fP (const optional< std::string > &optFcDirPath)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "optional< Result< \fBModelInputBundle\fP > > LoadBundle (const optional< std::string > & optFcDirPath)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
