.TH "IppaUV" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IppaUV
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sharedGuiTypes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBu\fP"
.br
.ti -1c
.RI "double \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
структура координат помехи 
.SH "Member Data Documentation"
.PP 
.SS "double IppaUV::u"
координаты помехи 
.SS "double IppaUV::v"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
