.TH "src/isDivMode.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/isDivMode.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'controlMsgModelTypes\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBModelNS23817A620S1823\fP"
.br
.ti -1c
.RI "namespace \fBModelNS23817A620S1823::IsDivMode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::mrik1_1\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::mrik2_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::mrik4_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::mrik6_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::mrik12_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::mrik12_8\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::m1_1\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::m6_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::m12_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::m12_8\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::sm1_1\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::sm2_1\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::sm6_3\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::sm6_6\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBModelNS23817A620S1823::IsDivMode::noDiv\fP (uint32_t divisionCoef)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
