.TH "libutils::ToJSON< SetOutputDirParams >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libutils::ToJSON< SetOutputDirParams >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Result< picojson::value > \fBresult_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBresult_type\fP \fBconvert\fP (const \fBSetOutputDirParams\fP &src)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef Result<picojson::value> libutils::ToJSON< \fBSetOutputDirParams\fP >::result_type"

.SH "Member Function Documentation"
.PP 
.SS "ToJSON< \fBSetOutputDirParams\fP >\fB::result_type\fP libutils::ToJSON< \fBSetOutputDirParams\fP >::convert (const \fBSetOutputDirParams\fP & src)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
