.TH "libutils::FromJSON< Polarized< T > >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libutils::FromJSON< Polarized< T > >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Result< \fBPolarized\fP< T >, JSONMismatchError > \fBresult_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBresult_type\fP \fBconvert\fP (const picojson::value &src)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<class T > typedef Result<\fBPolarized\fP<T>, JSONMismatchError> libutils::FromJSON< \fBPolarized\fP< T > >::result_type"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > static \fBresult_type\fP libutils::FromJSON< \fBPolarized\fP< T > >::convert (const picojson::value & src)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
