.TH "libutils::FromJSON< TargetStrobeOutput >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libutils::FromJSON< TargetStrobeOutput >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Result< \fBTargetStrobeOutput\fP, JSONMismatchError > \fBresult_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBresult_type\fP \fBconvert\fP (const picojson::value &src)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef Result<\fBTargetStrobeOutput\fP, JSONMismatchError> libutils::FromJSON< \fBTargetStrobeOutput\fP >::result_type"

.SH "Member Function Documentation"
.PP 
.SS "FromJSON< \fBTargetStrobeOutput\fP >\fB::result_type\fP libutils::FromJSON< \fBTargetStrobeOutput\fP >::convert (const picojson::value & src)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
