.TH "src/gui/mainwin.cpp" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui/mainwin.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QFileDialog>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QListWidget>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QPlastiqueStyle>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <libvork/e2ippa\&.h>\fP
.br
\fC#include <model/modelSharedConst\&.h>\fP
.br
\fC#include 'mainwin\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
