.TH "ModelNS23817A620S1823::CMsgSharedTypes::ImitTact" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::CMsgSharedTypes::ImitTact
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <controlMsgSharedTypes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBtexec\fP"
.br
.ti -1c
.RI "uint16_t \fBdigSpatProcNorm\fP"
.br
.ti -1c
.RI "uint16_t \fBreserve\fP"
.br
.ti -1c
.RI "bool \fBchanMask\fP [\fBSharedConst::maxChannelsInCellSM\fP]"
.br
.ti -1c
.RI "bool \fBchanMaskForAutocomp\fP [\fBSharedConst::maxChannelsInCellSM\fP][maxActiveInterferences]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Параметры имитируемого такта\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool ModelNS23817A620S1823::CMsgSharedTypes::ImitTact::chanMask[\fBSharedConst::maxChannelsInCellSM\fP]"
маска каналов текущей 412(223)й ячейки 
.SS "bool ModelNS23817A620S1823::CMsgSharedTypes::ImitTact::chanMaskForAutocomp[\fBSharedConst::maxChannelsInCellSM\fP][maxActiveInterferences]"
маска каналов ячейки для режима автокомпенсации 
.SS "uint16_t ModelNS23817A620S1823::CMsgSharedTypes::ImitTact::digSpatProcNorm"
норма для цифровой пространственной обработки и помехи 
.SS "uint16_t ModelNS23817A620S1823::CMsgSharedTypes::ImitTact::reserve"
резервное поле 
.SS "uint64_t ModelNS23817A620S1823::CMsgSharedTypes::ImitTact::texec"
такт исполнения 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
