.TH "ModelNS23817A620S1823::VirtualCell412_06" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::VirtualCell412_06
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <c412_06\&.h>\fP
.PP
Inherited by \fBModelNS23817A620S1823::Cell412_06\fP, and \fBModelNS23817A620S1823::WrappedLocalCell412_06\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~VirtualCell412_06\fP ()"
.br
.ti -1c
.RI "virtual void \fBgetResults\fP (\fBC412_06Result\fP *result)=0"
.br
.ti -1c
.RI "virtual void \fBsaveAdaptiveVectors\fP (std::complex< int32_t >[][\fBSharedConst::maxChannelsSM\fP])"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ModelNS23817A620S1823::VirtualCell412_06::~VirtualCell412_06 ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void ModelNS23817A620S1823::VirtualCell412_06::getResults (\fBC412_06Result\fP * result)\fC [pure virtual]\fP"

.PP
Implemented in \fBModelNS23817A620S1823::Cell412_06\fP, and \fBModelNS23817A620S1823::WrappedLocalCell412_06\fP\&.
.SS "virtual void ModelNS23817A620S1823::VirtualCell412_06::saveAdaptiveVectors (std::complex< int32_t >[][SharedConst::maxChannelsSM])\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBModelNS23817A620S1823::Cell412_06\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
