.TH "ModelNS23817A620S1823::CMsgSharedTypes" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::CMsgSharedTypes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBChanCoords\fP"
.br
.ti -1c
.RI "struct \fBImitObject\fP"
.br
.ti -1c
.RI "struct \fBImitStrobe\fP"
.br
.ti -1c
.RI "struct \fBImitTact\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
