.TH "include/model/modelSharedConst.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/model/modelSharedConst.h
.SH SYNOPSIS
.br
.PP
\fC#include <model/minDefs\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <libvork/e2trpr\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBModelNS23817A620S1823\fP"
.br
.ti -1c
.RI "namespace \fBModelNS23817A620S1823::SharedConst\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBModelNS23817A620S1823::SharedConst::ObjectTypes\fP { \fBModelNS23817A620S1823::SharedConst::signal\fP, \fBModelNS23817A620S1823::SharedConst::interference\fP }"
.br
.ti -1c
.RI "enum \fBModelNS23817A620S1823::SharedConst::PolarsCombining\fP { \fBModelNS23817A620S1823::SharedConst::incoherentSumming\fP, \fBModelNS23817A620S1823::SharedConst::coherentSummingWTlp\fP }"
.br
.ti -1c
.RI "enum \fBModelNS23817A620S1823::SharedConst::PhasingType\fP { \fBModelNS23817A620S1823::SharedConst::twoStage\fP = 0, \fBModelNS23817A620S1823::SharedConst::oneStageFromCenter\fP = 1, \fBModelNS23817A620S1823::SharedConst::oneStageByCodes\fP = 2 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBModelNS23817A620S1823::SharedConst::samplingFreq\fP [] = { 60000000\&., 50000000\&., 100000000\&. }"
.br
.ti -1c
.RI "const double \fBModelNS23817A620S1823::SharedConst::heterFreqStep\fP []"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxChannelsSM\fP = 1080"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxChannelsM\fP = 192"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxChannelsMrik\fP = 96"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxChannels\fP []"
.br
.ti -1c
.RI "const double \fBModelNS23817A620S1823::SharedConst::hardwGenFreqStep\fP []"
.br
.ti -1c
.RI "const double \fBModelNS23817A620S1823::SharedConst::radiationFreq\fP []"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxChannelsInCellSM\fP = 15"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxChannelsInCellM\fP = 4"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxChannelsInCellMrik\fP = 8"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxChannelsInCell\fP []"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxPolars\fP = 2"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxRays\fP = 16"
.br
.ti -1c
.RI "const uint32_t \fBModelNS23817A620S1823::SharedConst::maxDFGroups\fP = 10"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
