.TH "ModelNS23817A620S1823::Mark" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::Mark
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <b232\&.h>\fP
.PP
Inherited by \fBModelNS23817A620S1823::ComplexMark\fP, and \fBModelNS23817A620S1823::Monomark\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBdistance\fP"
.br
.ti -1c
.RI "uint32_t \fBfilter\fP"
.br
.ti -1c
.RI "uint32_t \fBray\fP"
.br
.ti -1c
.RI "double \fBmagnitude\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Базовая структура данных отметки\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t ModelNS23817A620S1823::Mark::distance"
дальность 
.SS "uint32_t ModelNS23817A620S1823::Mark::filter"
фильтр 
.SS "double ModelNS23817A620S1823::Mark::magnitude"
'Мощность отметки' - амплитуда, используемая для сортировки отметок перед их занесением в УЦОПО\&. Для комплексной отметки это амплитуда в центре креста, для моноотметки - амплитуда, превысившая порог\&. 
.SS "uint32_t ModelNS23817A620S1823::Mark::ray"
номер луча с максимумом 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
