.TH "ModelNS23817A620S1823::Value" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::Value
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <callbacks\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBtag\fP { \fBINT32\fP, \fBINT64\fP, \fBCOMPLEX32X32I\fP, \fBCOMPLEX32X32DF\fP, \fBINT32\fP, \fBINT64\fP, \fBCOMPLEX32X32I\fP, \fBCOMPLEX32X32DF\fP }"
.br
.ti -1c
.RI "enum \fBtag\fP { \fBINT32\fP, \fBINT64\fP, \fBCOMPLEX32X32I\fP, \fBCOMPLEX32X32DF\fP, \fBINT32\fP, \fBINT64\fP, \fBCOMPLEX32X32I\fP, \fBCOMPLEX32X32DF\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int32_t \fBi32val\fP"
.br
.ti -1c
.RI "   int64_t \fBi64val\fP"
.br
.ti -1c
.RI "   \fBComplex32x32i\fP \fBc32x32ival\fP"
.br
.ti -1c
.RI "   \fBComplex32x32df\fP \fBc32x32dfval\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int32_t \fBi32val\fP"
.br
.ti -1c
.RI "   int64_t \fBi64val\fP"
.br
.ti -1c
.RI "   \fBComplex32x32i\fP \fBc32x32ival\fP"
.br
.ti -1c
.RI "   \fBComplex32x32df\fP \fBc32x32dfval\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Универсальный тип данных, позволяющий хранить в себе значения нескольких других типов 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBModelNS23817A620S1823::Value::tag\fP"
обозначение типа данных в объединении 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINT32 \fP\fP
.TP
\fB\fIINT64 \fP\fP
.TP
\fB\fICOMPLEX32X32I \fP\fP
.TP
\fB\fICOMPLEX32X32DF \fP\fP
.TP
\fB\fIINT32 \fP\fP
.TP
\fB\fIINT64 \fP\fP
.TP
\fB\fICOMPLEX32X32I \fP\fP
.TP
\fB\fICOMPLEX32X32DF \fP\fP
.SS "enum \fBModelNS23817A620S1823::Value::tag\fP"
обозначение типа данных в объединении 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINT32 \fP\fP
.TP
\fB\fIINT64 \fP\fP
.TP
\fB\fICOMPLEX32X32I \fP\fP
.TP
\fB\fICOMPLEX32X32DF \fP\fP
.TP
\fB\fIINT32 \fP\fP
.TP
\fB\fIINT64 \fP\fP
.TP
\fB\fICOMPLEX32X32I \fP\fP
.TP
\fB\fICOMPLEX32X32DF \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "union  { \&.\&.\&. }  \fBModelNS23817A620S1823::Value\fP"
хранимое значение 
.SS "union  { \&.\&.\&. }  \fBModelNS23817A620S1823::Value\fP"
хранимое значение 
.SS "\fBComplex32x32df\fP ModelNS23817A620S1823::Value::c32x32dfval"
комплексное значение чисел с плавающей точкой двойной точности 
.SS "\fBComplex32x32i\fP ModelNS23817A620S1823::Value::c32x32ival"
значение комплексного целого со знаком 
.SS "int32_t ModelNS23817A620S1823::Value::i32val"
значение 32битного целого со знаком 
.SS "int64_t ModelNS23817A620S1823::Value::i64val"
значение 64битного целого со знаком 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
