.TH "ModelOutput" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelOutput \- Выдача, сгенерированная моделью по всем стробам одного такта\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RPC\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBex\fP"
.br
.ti -1c
.RI "std::list< \fBStrobeResult\fP > \fBstrobes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Выдача, сгенерированная моделью по всем стробам одного такта\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint64_t ModelOutput::ex"

.SS "std::list<\fBStrobeResult\fP> ModelOutput::strobes"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
