.TH "ModelNS23817A620S1823::SavePermissions" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::SavePermissions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <minDefs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBadcSlice\fP"
.br
.ti -1c
.RI "bool \fBquadrCompFormSlice\fP"
.br
.ti -1c
.RI "bool \fBpftpSlice\fP"
.br
.ti -1c
.RI "bool \fBpspSlice\fP"
.br
.ti -1c
.RI "bool \fBc418_01InputSlice\fP"
.br
.ti -1c
.RI "bool \fBc418_02InputSlice\fP"
.br
.ti -1c
.RI "bool \fBc418_02OutputSlice\fP"
.br
.ti -1c
.RI "bool \fBtfpSlice\fP"
.br
.ti -1c
.RI "bool \fBdirectivityPattern\fP"
.br
.ti -1c
.RI "bool \fBsaveToFilesPerm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Интерфейсная структура разрешений на сохранение срезов в файлы\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool ModelNS23817A620S1823::SavePermissions::adcSlice"
срез после АЦП 
.SS "bool ModelNS23817A620S1823::SavePermissions::c418_01InputSlice"
срез после входа ячейки 418-01 
.SS "bool ModelNS23817A620S1823::SavePermissions::c418_02InputSlice"
срез после входа ячейки 418-02 
.SS "bool ModelNS23817A620S1823::SavePermissions::c418_02OutputSlice"
срез после выхода ячейки 418-02 
.SS "bool ModelNS23817A620S1823::SavePermissions::directivityPattern"
диаграмма направленности 
.SS "bool ModelNS23817A620S1823::SavePermissions::pftpSlice"
срез после ПЧВО 
.SS "bool ModelNS23817A620S1823::SavePermissions::pspSlice"
срез после ППО 
.SS "bool ModelNS23817A620S1823::SavePermissions::quadrCompFormSlice"
срез после формирования квадратурных составляющих 
.SS "bool ModelNS23817A620S1823::SavePermissions::saveToFilesPerm"
сохранение в файлы, актуально только для сетевой версии true - сохранять; false - не сохранять 
.SS "bool ModelNS23817A620S1823::SavePermissions::tfpSlice"
срез после ЧВО 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
