.TH "ModelNS23817A620S1823::AdaptiveSpatProcVect::OneStrobeVectors" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::AdaptiveSpatProcVect::OneStrobeVectors
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <adaptiveSpatProcVect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBtExecNum\fP"
.br
.ti -1c
.RI "uint32_t \fBstrbID\fP"
.br
.ti -1c
.RI "bool \fBisBusy\fP"
.br
.ti -1c
.RI "\fBMode\fP \fBadaptMode\fP"
.br
.ti -1c
.RI "bool \fBpolarIsReady\fP [\fBSharedConst::maxPolars\fP]"
.br
.ti -1c
.RI "std::complex< int32_t > \fBadaptiveSpatProcVect\fP [\fBSharedConst::maxPolars\fP][\fBSharedConst::maxRays\fP][\fBSharedConst::maxChannelsSM\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Структура данных для хранения в себе адаптивных векторов ПО одного строба\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::complex<int32_t> ModelNS23817A620S1823::AdaptiveSpatProcVect::OneStrobeVectors::adaptiveSpatProcVect[\fBSharedConst::maxPolars\fP][\fBSharedConst::maxRays\fP][\fBSharedConst::maxChannelsSM\fP]"
вектора ПО, рассчитанные при адаптации (адаптивные)\&. Каналы в массиве расположены по порядку нумерации ячеек в крейте\&. Количество каналов взято как для сантиметровой станции, т\&.к\&. в ней их больше, чем в метровой и МРИК\&. 
.SS "\fBMode\fP ModelNS23817A620S1823::AdaptiveSpatProcVect::OneStrobeVectors::adaptMode"
вид адаптации, вектора которого находятся в структуре\&. 
.SS "bool ModelNS23817A620S1823::AdaptiveSpatProcVect::OneStrobeVectors::isBusy"
флаг заполненности массива данными\&. 
.SS "bool ModelNS23817A620S1823::AdaptiveSpatProcVect::OneStrobeVectors::polarIsReady[\fBSharedConst::maxPolars\fP]"
флаги готовности адаптивных векторов для поляризаций\&. 
.SS "uint32_t ModelNS23817A620S1823::AdaptiveSpatProcVect::OneStrobeVectors::strbID"
идентификатор строба, для которого предназначены адаптивные вектора ПО\&. 
.SS "uint64_t ModelNS23817A620S1823::AdaptiveSpatProcVect::OneStrobeVectors::tExecNum"
номер исполнения такта\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
