.TH "ModelNS23817A620S1823::Interface" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::Interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modelInterface\&.h>\fP
.PP
Inherited by \fBModelNS23817A620S1823::Main\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBInitLevel\fP { \fBcontrolMsgsOnly\fP, \fBfullInit\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Interface\fP ()"
.br
.ti -1c
.RI "virtual int32_t \fBformAllControlMessages\fP (\fBExternalMessages\fP *extMsgs, const \fBChannelsMask\fP *latticeMask, std::vector< \fBControlMessage\fP > &cntrlMsgs)=0"
.br
.ti -1c
.RI "virtual int32_t \fBstartProcessing\fP (\fBExternalMessages\fP *extMsgs, \fBCallbacks\fP *cbacks)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Класс интерфейса модели\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBModelNS23817A620S1823::Interface::InitLevel\fP"
уровень инициализации объекта модели\&. controlMsgsOnly - расчёт только УС fullInit - инициализация помимо памяти УС ещё и памяти для работы модели 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIcontrolMsgsOnly \fP\fP
.TP
\fB\fIfullInit \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ModelNS23817A620S1823::Interface::~Interface ()\fC [inline]\fP, \fC [virtual]\fP"
Деструктор объекта класса\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual int32_t ModelNS23817A620S1823::Interface::formAllControlMessages (\fBExternalMessages\fP * extMsgs, const \fBChannelsMask\fP * latticeMask, std::vector< \fBControlMessage\fP > & cntrlMsgs)\fC [pure virtual]\fP"
Формирование УС для всех стробов такта и всех ячеек\&. 
.PP
\fBParameters\fP
.RS 4
\fIextMsgs\fP указатель на объект структуры входных сообщений 
.br
\fIcntrlMsgs\fP ссылка на объект управляющего сообщения 
.RE
.PP
\fBReturns\fP
.RS 4
\fBMain::ok\fP (0) если модель завершила расчёт УС, \fBMain::locked\fP (1) в противном случае 
.RE
.PP

.PP
Implemented in \fBModelNS23817A620S1823::Main\fP\&.
.SS "virtual int32_t ModelNS23817A620S1823::Interface::startProcessing (\fBExternalMessages\fP * extMsgs, \fBCallbacks\fP * cbacks)\fC [pure virtual]\fP"
Запуск модели для расчёта одного такта работы приёмника станции\&. Передаваемые сетевые сообщения должны просуществовать как минимум до конца формирования УС\&. 
.PP
\fBParameters\fP
.RS 4
\fIextMsgs\fP указатель на объект структуры входных сообщений 
.br
\fIcbacks\fP указатель на объект структуры коллбэков для срезов 
.RE
.PP
\fBReturns\fP
.RS 4
\fBMain::ok\fP (0) если модель завершила расчёт, \fBMain::locked\fP (1) в противном случае 
.RE
.PP

.PP
Implemented in \fBModelNS23817A620S1823::Main\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
