.TH "ModelNS23817A620S1823::CMsgSharedTypes::ChanCoords" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::CMsgSharedTypes::ChanCoords
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <controlMsgSharedTypes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Координаты канала на антенном полотне\&. 
.SH "Member Data Documentation"
.PP 
.SS "double ModelNS23817A620S1823::CMsgSharedTypes::ChanCoords::x"
координата канала по оси x 
.SS "double ModelNS23817A620S1823::CMsgSharedTypes::ChanCoords::y"
координата канала по оси y 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
