.TH "ModelNS23817A620S1823::IsDivMode" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::IsDivMode
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBmrik1_1\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBmrik2_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBmrik4_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBmrik6_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBmrik12_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBmrik12_8\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBm1_1\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBm6_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBm12_4\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBm12_8\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBsm1_1\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBsm2_1\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBsm6_3\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBsm6_6\fP (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
.br
.ti -1c
.RI "bool \fBnoDiv\fP (uint32_t divisionCoef)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Область имён функций проверки типа режимов дробления полотна\&. 
.SH "Function Documentation"
.PP 
.SS "bool ModelNS23817A620S1823::IsDivMode::m12_4 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 12;4 для станции Воронеж-М\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 12;4 Воронеж-М, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::m12_8 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 12;8 для станции Воронеж-М\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 12;8 Воронеж-М, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::m1_1 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 1;1 для станции Воронеж-М\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 1;1 Воронеж-М, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::m6_4 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 6;4 для станции Воронеж-М\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 6;4 Воронеж-М, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::mrik12_4 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 12;4 для станции МРИК\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 12;4 МРИК, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::mrik12_8 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 12;8 для станции МРИК\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 12;8 МРИК, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::mrik1_1 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 1;1 для станции МРИК\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 1;1 МРИК, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::mrik2_4 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 2;4 для станции МРИК\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 2;4 МРИК, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::mrik4_4 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 4;4 для станции МРИК\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 4;4 МРИК, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::mrik6_4 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 6;4 для станции МРИК\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 6;4 МРИК, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::noDiv (uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что это режим без разбиения, т\&.е\&. всё полотно является единым фрагментов\&. Для всех станций\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим без дробления полотна для всех станций, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::sm1_1 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 1;1 для станции Воронеж-СМ\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 1;1 Воронеж-СМ, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::sm2_1 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 2;1 для станции Воронеж-СМ\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 2;1 Воронеж-СМ, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::sm6_3 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 6;3 для станции Воронеж-СМ\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 6;3 Воронеж-СМ, false в противном случае 
.RE
.PP

.SS "bool ModelNS23817A620S1823::IsDivMode::sm6_6 (\fBSharedConst::StationType\fP stationType, uint32_t divisionCoef)"
Проверка режима дробления полотна на то, что он 6;6 для станции Воронеж-СМ\&. 
.PP
\fBParameters\fP
.RS 4
\fIstationType\fP тип станции 
.br
\fIdivisionCoef\fP коэффициент дробления полотна 
.RE
.PP
\fBReturns\fP
.RS 4
true если режим дробления полотна 6;6 Воронеж-СМ, false в противном случае 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
