.TH "ModelNS23817A620S1823::Retainer< T >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::Retainer< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unique_ptr< T, std::function< void(T *)> > \fBpointer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class\&.\&.\&. Args> \fBpointer\fP \fBget\fP (Args\&.\&.\&. args)"
.br
.ti -1c
.RI "void \fBput\fP (T *p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::list< T * > \fBpool\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
struct ModelNS23817A620S1823::Retainer< T >"Простейший пул, предназначенный для того, чтобы \fIне отдавать\fP память\&. При работе модели с деревом станции постоянно создаются и уничтожаются объекты ячеек (\fBCell412_06\fP и прочие), и, судя по выдаче time (значения sys в десятки раз больше, чем без дерева), постоянное выделение и освобождение блоков памяти в сотни мегабайт очень дорого по времени (real, реальному времени, хотя user меняется мало)\&. Поэтому делаем пул, который на самом деле не освобождает память, а придерживает ее для последующего переиспользования\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "template<class T > typedef unique_ptr<T, std::function<void (T *)> > \fBModelNS23817A620S1823::Retainer\fP< T >::pointer"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > template<class\&.\&.\&. Args> \fBpointer\fP \fBModelNS23817A620S1823::Retainer\fP< T >::get (Args\&.\&.\&. args)\fC [inline]\fP"

.SS "template<class T > void \fBModelNS23817A620S1823::Retainer\fP< T >::put (T * p)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<class T > std::list<T *> \fBModelNS23817A620S1823::Retainer\fP< T >::pool"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
