.TH "ModelWrapper" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelWrapper\fP ()"
.br
.ti -1c
.RI "Result< NoneType > \fBsetOutputDir\fP (const \fBSetOutputDirParams\fP &p)"
.br
.ti -1c
.RI "Result< \fBModelOutput\fP > \fBcomputePlanes\fP (const \fBModelInputBundle\fP &p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBstopFlag\fP"
.br
.ti -1c
.RI "optional< string > \fBoutDir\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModelWrapper::ModelWrapper ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "Result< \fBModelOutput\fP > ModelWrapper::computePlanes (const \fBModelInputBundle\fP & p)\fC [inline]\fP"

.SS "Result< NoneType > ModelWrapper::setOutputDir (const \fBSetOutputDirParams\fP & p)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "optional<string> ModelWrapper::outDir"

.SS "bool ModelWrapper::stopFlag"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
