.TH "ModelNS23817A620S1823::ChannelsMask" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::ChannelsMask
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modelInterface\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBmask\fP [\fBSharedConst::maxPolars\fP][\fBSharedConst::maxChannelsSM\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Интерфейсная структура маски каналов\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool ModelNS23817A620S1823::ChannelsMask::mask[\fBSharedConst::maxPolars\fP][\fBSharedConst::maxChannelsSM\fP]"
маска каналов по двум поляризациям 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
