.TH "ModelNS23817A620S1823::ExternalMessages" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::ExternalMessages
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modelInterface\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TrimtsMsg * \fBtrimts\fP"
.br
.ti -1c
.RI "E2TRPR * \fBtrpr\fP"
.br
.ti -1c
.RI "E2IPPA * \fBippa\fP"
.br
.ti -1c
.RI "\fBE2Trkp\fP * \fBklb\fP"
.br
.ti -1c
.RI "\fBE2Trkp\fP * \fBafr\fP"
.br
.ti -1c
.RI "\fBChannelsMask\fP * \fBchMask\fP"
.br
.ti -1c
.RI "\fBStationParams\fP * \fBstationParams\fP"
.br
.ti -1c
.RI "std::list< \fBStrobeResult\fP > * \fBresults\fP"
.br
.ti -1c
.RI "\fBUcopoMsgBuf\fP * \fBucopoBuf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Интерфейсная структура сетевых сообщений, которые необходимо передавать в модель\&.
.PP
\fBExternalMessages\fP не владеет этими сообщениями (т\&.е\&. не удаляет их)\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBE2Trkp\fP* ModelNS23817A620S1823::ExternalMessages::afr"
амплитудно-фазовое распеделение 
.SS "\fBChannelsMask\fP* ModelNS23817A620S1823::ExternalMessages::chMask"
маска каналов 
.SS "E2IPPA* ModelNS23817A620S1823::ExternalMessages::ippa"
координаты активных помех 
.SS "\fBE2Trkp\fP* ModelNS23817A620S1823::ExternalMessages::klb"
калибровочные вектора 
.SS "std::list<\fBStrobeResult\fP>* ModelNS23817A620S1823::ExternalMessages::results"
Выдача, сгенерированная моделью 
.SS "\fBStationParams\fP* ModelNS23817A620S1823::ExternalMessages::stationParams"
параметры модели станции 
.SS "TrimtsMsg* ModelNS23817A620S1823::ExternalMessages::trimts"
тактовое расписание имитатора АЦП 
.SS "E2TRPR* ModelNS23817A620S1823::ExternalMessages::trpr"
тактовое расписание приёмника 
.SS "\fBUcopoMsgBuf\fP* ModelNS23817A620S1823::ExternalMessages::ucopoBuf"
буфер для сообщения УЦОПО 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
