.TH "ModelNS23817A620S1823::WrappedLocalCell418_01" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::WrappedLocalCell418_01
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModelNS23817A620S1823::VirtualCell418_01\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWrappedLocalCell418_01\fP (const \fBControlMsg\fP &cmsg, int crNum)"
.br
.ti -1c
.RI "virtual \fB~WrappedLocalCell418_01\fP ()"
.br
.ti -1c
.RI "virtual void \fBgetResults\fP (\fBC412_06Result\fP *result)"
.br
.in -1c

Public Member Functions inherited from \fBModelNS23817A620S1823::VirtualCell418_01\fP
.in +1c
.ti -1c
.RI "virtual \fB~VirtualCell418_01\fP ()"
.br
.ti -1c
.RI "void \fBsendAdaptiveVectors2ZCell412\fP (std::complex< int32_t >[][\fBSharedConst::maxChannelsSM\fP])"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const \fBControlMsg\fP \fBcontrolMsg\fP"
.br
.ti -1c
.RI "int \fBcrateNum\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBRetainer\fP< \fBCell418_01\fP > \fBpool\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBModelNS23817A620S1823::VirtualCell418_01\fP
.in +1c
.ti -1c
.RI "std::vector< std::unique_ptr< \fBVirtualCell412_06\fP > > \fBc412\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModelNS23817A620S1823::WrappedLocalCell418_01::WrappedLocalCell418_01 (const \fBControlMsg\fP & cmsg, int crNum)\fC [inline]\fP"

.SS "virtual ModelNS23817A620S1823::WrappedLocalCell418_01::~WrappedLocalCell418_01 ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void ModelNS23817A620S1823::WrappedLocalCell418_01::getResults (\fBC412_06Result\fP * result)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBModelNS23817A620S1823::VirtualCell418_01\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBControlMsg\fP ModelNS23817A620S1823::WrappedLocalCell418_01::controlMsg\fC [private]\fP"

.SS "int ModelNS23817A620S1823::WrappedLocalCell418_01::crateNum\fC [private]\fP"

.SS "\fBRetainer\fP< \fBCell418_01\fP > ModelNS23817A620S1823::WrappedLocalCell418_01::pool\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
