.TH "ModelNS23817A620S1823::ControlMsg::HeterodyneDataHolder" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::ControlMsg::HeterodyneDataHolder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <controlMsg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::complex< int32_t > \fBdata\fP [\fBSharedConst::discretesInTact\fP]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::complex<int32_t> ModelNS23817A620S1823::ControlMsg::HeterodyneDataHolder::data[\fBSharedConst::discretesInTact\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
