.TH "ModelNS23817A620S1823::C418_02Result" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::C418_02Result
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <c418_02Result\&.h>\fP
.PP
Inherits \fBModelNS23817A620S1823::C412_06Result\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear418Results\fP ()"
.br
.ti -1c
.RI "void \fBdumpTargetSigmas\fP (\fBSliceFile\fP &sFile, uint32_t raysNum)"
.br
.ti -1c
.RI "\fBC418_02Result\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBModelNS23817A620S1823::C412_06Result\fP
.in +1c
.ti -1c
.RI "void \fBclear412Results\fP ()"
.br
.ti -1c
.RI "void \fBclearInterfSpectrumNorms\fP ()"
.br
.ti -1c
.RI "void \fBdumpInterfSpectrumNorms\fP (\fBSliceFile\fP &sFile, uint32_t length, uint32_t raysNum)"
.br
.ti -1c
.RI "void \fBdumpTargData\fP (\fBSliceFile\fP &sFile, uint32_t raysNum, uint32_t samplesNum)"
.br
.ti -1c
.RI "void \fBclearTargData\fP ()"
.br
.ti -1c
.RI "void \fBprintCalibrLIMMSourceData\fP (\fBSharedConst::StationType\fP stType) const"
.br
.ti -1c
.RI "\fBC412_06Result\fP ()"
.br
.ti -1c
.RI "virtual \fB~C412_06Result\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBtargetSigmas\fP [\fBSharedConst::maxRays\fP]"
.br
.in -1c

Public Attributes inherited from \fBModelNS23817A620S1823::C412_06Result\fP
.in +1c
.ti -1c
.RI "uint64_t \fBinterfSpectrumNorms\fP [\fBSharedConst::maxRays\fP *\fBSharedConst::maxDFGroups\fP][\fBSharedConst::maxFragmKgrs\fP]"
.br
.ti -1c
.RI "std::complex< int32_t > \fBtargData\fP [\fBSharedConst::maxRays\fP][\fBSharedConst::maxSamplesInRay\fP]"
.br
.ti -1c
.RI "std::complex< int32_t > \fBadaptData\fP [\fBSharedConst::maxRays\fP+maxActiveInterferences+\fBSharedConst::sigAdaptExtraRows\fP][\fBSharedConst::maxChannelsInCellSM\fP *\fBSharedConst::maxCellsInCrateSM\fP]"
.br
.ti -1c
.RI "std::complex< double > \fBcalibrLIMMData\fP [\fBSharedConst::maxChannelsSM\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Структура выходной информации ячейки суммирования крейтов 418-02\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModelNS23817A620S1823::C418_02Result::C418_02Result ()"
Конструктор объекта структуры\&. 
.SH "Member Function Documentation"
.PP 
.SS "void ModelNS23817A620S1823::C418_02Result::clear418Results ()"
Очистка массивов структуры\&. 
.SS "void ModelNS23817A620S1823::C418_02Result::dumpTargetSigmas (\fBSliceFile\fP & sFile, uint32_t raysNum)"
Сохранение в файл, который описывает sFile, данных массива targetSigmas\&. 
.PP
\fBParameters\fP
.RS 4
\fIsFile\fP ссылка на объект файла среза 
.br
\fIraysNum\fP количество лучей 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "uint64_t ModelNS23817A620S1823::C418_02Result::targetSigmas[\fBSharedConst::maxRays\fP]"
сигмы целевого режима 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
