.TH "ModelNS23817A620S1823::TargetStrobeOutputExt" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::TargetStrobeOutputExt
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <b232\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TStrobe \fBfc\fP"
.br
.ti -1c
.RI "\fBPolarized\fP< \fBVector3d\fP< std::complex< double > > > \fBplanes\fP"
.br
.ti -1c
.RI "\fBPolarized\fP< std::vector< uint64_t > > \fBsigmas\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "TStrobe ModelNS23817A620S1823::TargetStrobeOutputExt::fc"

.SS "\fBPolarized\fP<\fBVector3d\fP<std::complex<double> > > ModelNS23817A620S1823::TargetStrobeOutputExt::planes"

.SS "\fBPolarized\fP<std::vector<uint64_t> > ModelNS23817A620S1823::TargetStrobeOutputExt::sigmas"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
