.TH "ModelNS23817A620S1823::Monomark" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::Monomark
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <b232\&.h>\fP
.PP
Inherits \fBModelNS23817A620S1823::Mark\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMonomark\fP (uint nrays, uint kgrs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector2d\fP< double > \fBamplitude\fP"
.br
.ti -1c
.RI "\fBPolarized\fP< \fBVector2d\fP< std::complex< double > > > \fBrawAmplitude\fP"
.br
.ti -1c
.RI "\fBVector2d\fP< double > \fBthreshold\fP"
.br
.in -1c

Public Attributes inherited from \fBModelNS23817A620S1823::Mark\fP
.in +1c
.ti -1c
.RI "uint32_t \fBdistance\fP"
.br
.ti -1c
.RI "uint32_t \fBfilter\fP"
.br
.ti -1c
.RI "uint32_t \fBray\fP"
.br
.ti -1c
.RI "double \fBmagnitude\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Структура моноотметки\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModelNS23817A620S1823::Monomark::Monomark (uint nrays, uint kgrs)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBVector2d\fP<double> ModelNS23817A620S1823::Monomark::amplitude"
амплитуды в фильтрах во всех лучах; [лучи][скорости] 
.SS "\fBPolarized\fP<\fBVector2d\fP<std::complex<double> > > ModelNS23817A620S1823::Monomark::rawAmplitude"
сырые амплитуды в поляризациях; [поляризации][лучи][скорости] 
.SS "\fBVector2d\fP<double> ModelNS23817A620S1823::Monomark::threshold"
порог для значений в фильтрах во всех лучах; [лучи][скорости] 

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
