.TH "ModelNS23817A620S1823::WrappedLocalCell412_06" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelNS23817A620S1823::WrappedLocalCell412_06
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModelNS23817A620S1823::VirtualCell412_06\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWrappedLocalCell412_06\fP (const \fBControlMsg\fP &cmsg, int crNum, int clNum)"
.br
.ti -1c
.RI "virtual \fB~WrappedLocalCell412_06\fP ()"
.br
.ti -1c
.RI "virtual void \fBgetResults\fP (\fBC412_06Result\fP *result)"
.br
.in -1c

Public Member Functions inherited from \fBModelNS23817A620S1823::VirtualCell412_06\fP
.in +1c
.ti -1c
.RI "virtual \fB~VirtualCell412_06\fP ()"
.br
.ti -1c
.RI "virtual void \fBsaveAdaptiveVectors\fP (std::complex< int32_t >[][\fBSharedConst::maxChannelsSM\fP])"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBControlMsg\fP \fBcontrolMsg\fP"
.br
.ti -1c
.RI "int \fBcrateNum\fP"
.br
.ti -1c
.RI "int \fBcellNum\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBRetainer\fP< \fBCell412_06\fP > \fBpool\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModelNS23817A620S1823::WrappedLocalCell412_06::WrappedLocalCell412_06 (const \fBControlMsg\fP & cmsg, int crNum, int clNum)\fC [inline]\fP"

.SS "virtual ModelNS23817A620S1823::WrappedLocalCell412_06::~WrappedLocalCell412_06 ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void ModelNS23817A620S1823::WrappedLocalCell412_06::getResults (\fBC412_06Result\fP * result)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBModelNS23817A620S1823::VirtualCell412_06\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ModelNS23817A620S1823::WrappedLocalCell412_06::cellNum\fC [private]\fP"

.SS "\fBControlMsg\fP ModelNS23817A620S1823::WrappedLocalCell412_06::controlMsg\fC [private]\fP"

.SS "int ModelNS23817A620S1823::WrappedLocalCell412_06::crateNum\fC [private]\fP"

.SS "\fBRetainer\fP< \fBCell412_06\fP > ModelNS23817A620S1823::WrappedLocalCell412_06::pool\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
