.TH "src/gui/progressCallback.cpp" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui/progressCallback.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'guiapp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsendUpdateProgressBarSignal\fP ()"
.br
.ti -1c
.RI "void \fBsendProgressBarMaxChangedSignal\fP (uint32_t maxValue)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sendProgressBarMaxChangedSignal (uint32_t maxValue)"

.SS "bool sendUpdateProgressBarSignal ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
