.TH "ResourceUsage" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResourceUsage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <runModel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ulong \fBrealTime\fP"
.br
.ti -1c
.RI "ulong \fBsysTime\fP"
.br
.ti -1c
.RI "ulong \fBuserTime\fP"
.br
.ti -1c
.RI "ulong \fBmaxRss\fP"
.br
.ti -1c
.RI "ulong \fBmajFaults\fP"
.br
.ti -1c
.RI "ulong \fBminFaults\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "ulong ResourceUsage::majFaults"

.SS "ulong ResourceUsage::maxRss"

.SS "ulong ResourceUsage::minFaults"

.SS "ulong ResourceUsage::realTime"

.SS "ulong ResourceUsage::sysTime"

.SS "ulong ResourceUsage::userTime"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
