.TH "SavedStationParams" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SavedStationParams
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint \fBstationType\fP"
.br
.ti -1c
.RI "bool \fBadcSlice\fP"
.br
.ti -1c
.RI "bool \fBquadrCompFormSlice\fP"
.br
.ti -1c
.RI "bool \fBpftpSlice\fP"
.br
.ti -1c
.RI "bool \fBpspSlice\fP"
.br
.ti -1c
.RI "bool \fBc418_01InputSlice\fP"
.br
.ti -1c
.RI "bool \fBc418_02InputSlice\fP"
.br
.ti -1c
.RI "bool \fBc418_02OutputSlice\fP"
.br
.ti -1c
.RI "bool \fBtfpSlice\fP"
.br
.ti -1c
.RI "bool \fBdirectivityPattern\fP"
.br
.ti -1c
.RI "bool \fBsaveToFilesPerm\fP"
.br
.ti -1c
.RI "uint \fBquadrCompFormType\fP"
.br
.ti -1c
.RI "bool \fBdelayCompensationPerm\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool SavedStationParams::adcSlice"

.SS "bool SavedStationParams::c418_01InputSlice"

.SS "bool SavedStationParams::c418_02InputSlice"

.SS "bool SavedStationParams::c418_02OutputSlice"

.SS "bool SavedStationParams::delayCompensationPerm"

.SS "bool SavedStationParams::directivityPattern"

.SS "bool SavedStationParams::pftpSlice"

.SS "bool SavedStationParams::pspSlice"

.SS "bool SavedStationParams::quadrCompFormSlice"

.SS "uint SavedStationParams::quadrCompFormType"

.SS "bool SavedStationParams::saveToFilesPerm"

.SS "uint SavedStationParams::stationType"

.SS "bool SavedStationParams::tfpSlice"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
