.TH "src/jsonrpc/serdes.cpp" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/jsonrpc/serdes.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <libutils/fdstream\&.h>\fP
.br
\fC#include 'serdes\&.h'\fP
.br
\fC#include <model/minDefs\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlibutils::ToJSON< Vector3d< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::FromJSON< Vector3d< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::ToJSON< Polarized< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::FromJSON< Polarized< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::ToJSON< SetOutputDirParams >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::FromJSON< SetOutputDirParams >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::ToJSON< ModelInputBundle >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::FromJSON< ModelInputBundle >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::ToJSON< TargetStrobeOutput >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::FromJSON< TargetStrobeOutput >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::ToJSON< InterfStrobeOutput >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::FromJSON< InterfStrobeOutput >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::ToJSON< CalibStrobeOutput >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::FromJSON< CalibStrobeOutput >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::ToJSON< ModelOutput >\fP"
.br
.ti -1c
.RI "struct \fBlibutils::FromJSON< ModelOutput >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlibutils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
