.TH "src/gui/sliceViewer.h" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui/sliceViewer.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <complex>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'gnuplot\-iostream\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSliceViewer\fP"
.br
.ti -1c
.RI "struct \fBSliceViewer::FileData\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
