.TH "SliceViewer::FileData" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SliceViewer::FileData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBdouble\fP > \fBdata2D\fP"
.br
.ti -1c
.RI "std::vector< std::complex< \fBdouble\fP > > \fBcData2D\fP"
.br
.ti -1c
.RI "std::vector< std::vector< \fBdouble\fP > > \fBdata3D\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::complex< \fBdouble\fP > > > \fBcData3D\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "\fBDataType\fP \fBdataType\fP"
.br
.ti -1c
.RI "\fBDataShape\fP \fBdataShape\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBmaxXValue\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBmaxYValue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::complex<\fBdouble\fP> > SliceViewer::FileData::cData2D"

.SS "std::vector<std::vector<std::complex<\fBdouble\fP> > > SliceViewer::FileData::cData3D"

.SS "std::vector<\fBdouble\fP> SliceViewer::FileData::data2D"

.SS "std::vector<std::vector<\fBdouble\fP> > SliceViewer::FileData::data3D"

.SS "\fBDataShape\fP SliceViewer::FileData::dataShape"

.SS "\fBDataType\fP SliceViewer::FileData::dataType"

.SS "\fBuint32_t\fP SliceViewer::FileData::maxXValue"

.SS "\fBuint32_t\fP SliceViewer::FileData::maxYValue"

.SS "std::string SliceViewer::FileData::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
