.TH "src/sliceFile.cpp" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sliceFile.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'sliceFile\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBModelNS23817A620S1823\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
