.TH "src/gui/sliceViewer.cpp" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui/sliceViewer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <ios>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include 'sliceViewer\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static const char * \fBPAUSE_MOUSE\fP = 'pause mouse keypress\\n'"
.br
.ti -1c
.RI "static const char * \fBVORK_MODEL\fP = 'vork\-model\&.tmp'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* PAUSE_MOUSE = 'pause mouse keypress\\n'\fC [static]\fP"

.SS "const char* VORK_MODEL = 'vork\-model\&.tmp'\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
