.TH "StrobeInfo" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StrobeInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <messages\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStrobeInfo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TStrobe \fBtrprStrb\fP"
.br
.ti -1c
.RI "ImitStrobe \fBtrimtsStrb\fP"
.br
.ti -1c
.RI "bool \fBtrimtsAvailable\fP"
.br
.ti -1c
.RI "std::vector< \fBObjectInfo\fP > \fBobject\fP"
.br
.ti -1c
.RI "std::string \fBdescr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StrobeInfo::StrobeInfo ()"

.SH "Member Data Documentation"
.PP 
.SS "std::string StrobeInfo::descr"

.SS "std::vector<\fBObjectInfo\fP> StrobeInfo::object"

.SS "bool StrobeInfo::trimtsAvailable"

.SS "ImitStrobe StrobeInfo::trimtsStrb"

.SS "TStrobe StrobeInfo::trprStrb"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
