.TH "TactInfo" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TactInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <messages\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTactInfo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDTRPR \fBtrprTact\fP"
.br
.ti -1c
.RI "ImitTactDescription \fBtrimtsTact\fP"
.br
.ti -1c
.RI "std::vector< \fBStrobeInfo\fP > \fBstrobe\fP"
.br
.ti -1c
.RI "std::string \fBdescr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TactInfo::TactInfo ()"

.SH "Member Data Documentation"
.PP 
.SS "std::string TactInfo::descr"

.SS "std::vector<\fBStrobeInfo\fP> TactInfo::strobe"

.SS "ImitTactDescription TactInfo::trimtsTact"

.SS "SDTRPR TactInfo::trprTact"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
