.TH "Vector2d< T >" 3 "Test moduls" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector2d< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <minDefs\&.h>\fP
.PP
Inherits std::vector< std::vector< T > >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< std::vector< T > > \fBBase\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector2d\fP ()"
.br
.ti -1c
.RI "\fBVector2d\fP (const \fBBase\fP &oth)"
.br
.ti -1c
.RI "\fBVector2d\fP (\fBBase\fP &&oth)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBVector2d\fP< T > \fBmake\fP (uint d1, uint d2)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<class T > typedef std::vector<std::vector<T> > \fBVector2d\fP< T >::Base"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBVector2d\fP< T >\fB::Vector2d\fP ()\fC [inline]\fP"

.SS "template<class T > \fBVector2d\fP< T >\fB::Vector2d\fP (const \fBBase\fP & oth)\fC [inline]\fP"

.SS "template<class T > \fBVector2d\fP< T >\fB::Vector2d\fP (\fBBase\fP && oth)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > static \fBVector2d\fP< T > \fBVector2d\fP< T >::make (uint d1, uint d2)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Test moduls from the source code\&.
